name: Package and release

on:
  push:
    tags:
      - '**'
  workflow_dispatch: # manually

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fix locales
        run: |
          cp -f locales/locales/* locales/

      - name: Package and release
        uses: BigWigsMods/packager@v2

    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
